import os
import glob
from typing import List, Dict, Tuple, Any
from dotenv import load_dotenv
# pyrefly: ignore [missing-import]
from github import Github, Auth

load_dotenv()

def fetch_github_issue(issue_url: str, token: str = None) -> Tuple[str, str, str]:
    """
    Parses GitHub issue URL and fetches (repo_full_name, title, body) using PyGithub.
    Example URL: https://github.com/owner/repo/issues/1
    """
    if not token:
        token = os.getenv("GITHUB_TOKEN")
        
    parts = issue_url.rstrip("/").split("/")
    if len(parts) < 7 or parts[-2] != "issues":
        raise ValueError(f"Invalid GitHub issue URL format: {issue_url}")
        
    owner, repo_name, issue_num = parts[-4], parts[-3], int(parts[-1])
    repo_full_name = f"{owner}/{repo_name}"
    
    auth = Auth.Token(token) if token else None
    g = Github(auth=auth)
    repo = g.get_repo(repo_full_name)
    issue = repo.get_issue(number=issue_num)
    
    return repo_full_name, issue.title, issue.body or ""

def create_pull_request(issue_url: str, branch_name: str, patch_summary: str, token: str = None) -> str:
    """
    Creates a pull request on GitHub using PyGithub API.
    """
    if not token:
        token = os.getenv("GITHUB_TOKEN")
        
    if not token:
        return "https://github.com/pulls (Token not provided)"
        
    try:
        parts = issue_url.rstrip("/").split("/")
        owner, repo_name = parts[-4], parts[-3]
        repo_full_name = f"{owner}/{repo_name}"
        
        auth = Auth.Token(token)
        g = Github(auth=auth)
        repo = g.get_repo(repo_full_name)
        
        # Create PR from fix branch to default branch (main/master)
        default_branch = repo.default_branch
        pr = repo.create_pull(
            title=f"Fix: Auto-resolved {parts[-1]}",
            body=f"Automated resolution generated by Smart GitHub Issue Resolver.\n\nSummary:\n{patch_summary}",
            head=branch_name,
            base=default_branch
        )
        return pr.html_url
    except Exception as e:
        print(f"Failed to create GitHub PR: {e}")
        return f"https://github.com/{owner}/{repo_name}/pulls"

def inspect_repository(repo_path: str) -> Dict[str, Any]:
    """
    Scans repository directory and returns list of source files and file tree.
    """
    abs_path = os.path.abspath(repo_path)
    if not os.path.exists(abs_path):
        return {"file_tree": [], "files": {}}

    file_tree = []
    files_content = {}
    ignore_dirs = {'.git', '__pycache__', '.pytest_cache', 'venv', '.venv', 'node_modules'}
    
    for root, dirs, files in os.walk(abs_path):
        dirs[:] = [d for d in dirs if d not in ignore_dirs]
        for file in files:
            if file.endswith(('.py', '.js', '.ts', '.jsx', '.tsx', '.json', '.md')):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, abs_path)
                file_tree.append(rel_path)
                try:
                    with open(full_path, 'r', encoding='utf-8') as f:
                        files_content[rel_path] = f.read()
                except Exception:
                    pass

    return {
        "file_tree": sorted(file_tree),
        "files": files_content
    }

def apply_patch_to_file(repo_path: str, rel_filepath: str, new_content: str) -> bool:
    """
    Writes updated file content directly to target file inside the repository.
    """
    full_path = os.path.join(os.path.abspath(repo_path), rel_filepath)
    try:
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        return True
    except Exception as e:
        print(f"Error writing patch to {full_path}: {e}")
        return False
