import os
import glob
import re
import tempfile
import git
from typing import List, Dict, Tuple, Any
from dotenv import load_dotenv
# pyrefly: ignore [missing-import]
from github import Github, Auth

load_dotenv()


class PullRequestError(RuntimeError):
    """Raised when a local change cannot be published as a GitHub pull request."""

def parse_github_issue_url(issue_url: str) -> Tuple[str, str, int]:
    """
    Extracts (owner, repo, issue_number) from a GitHub issue URL.
    """
    match = re.search(r"github\.com/([^/]+)/([^/]+)/issues/(\d+)", issue_url)
    if not match:
        raise ValueError(f"Invalid GitHub issue URL format: {issue_url}")
    owner, repo, issue_num = match.groups()
    return owner, repo, int(issue_num)

def clone_github_repository(issue_url: str, token: str = None) -> str:
    """
    Clones a remote GitHub repository to a temporary local workspace.
    """
    if not token:
        token = os.getenv("GITHUB_TOKEN")
        
    owner, repo_name, _ = parse_github_issue_url(issue_url)
    
    if token:
        clone_url = f"https://x-access-token:{token}@github.com/{owner}/{repo_name}.git"
    else:
        clone_url = f"https://github.com/{owner}/{repo_name}.git"
        
    temp_dir = tempfile.mkdtemp(prefix=f"agent_repo_{repo_name}_")
    print(f"[Git] Cloning {owner}/{repo_name} into temporary directory {temp_dir}...")
    git.Repo.clone_from(clone_url, temp_dir)
    return temp_dir

def fetch_github_issue(issue_url: str, token: str = None) -> Tuple[str, str, str]:
    """
    Parses GitHub issue URL and fetches (repo_full_name, title, body) using PyGithub.
    Example URL: https://github.com/owner/repo/issues/1
    """
    if not token:
        token = os.getenv("GITHUB_TOKEN")
        
    owner, repo_name, issue_num = parse_github_issue_url(issue_url)
    repo_full_name = f"{owner}/{repo_name}"
    
    auth = Auth.Token(token) if token else None
    g = Github(auth=auth)
    repo = g.get_repo(repo_full_name)
    issue = repo.get_issue(number=issue_num)
    
    return repo_full_name, issue.title, issue.body or ""

def create_pull_request(issue_url: str, branch_name: str, patch_summary: str, repo_path: str = None, token: str = None) -> str:
    """
    Commits, pushes local changes to GitHub branch, and creates a Pull Request via PyGithub API.
    """
    if not token:
        token = os.getenv("GITHUB_TOKEN")
        
    if not token:
        raise PullRequestError("No GitHub token was provided. A token with repository write access is required.")

    if not repo_path or not os.path.isdir(repo_path):
        raise PullRequestError("The local cloned repository is unavailable; no changes can be committed or pushed.")

    try:
        owner, repo_name, issue_num = parse_github_issue_url(issue_url)
        repo_full_name = f"{owner}/{repo_name}"
        
        # 1. Commit and push local workspace changes to GitHub
        local_repo = git.Repo(repo_path)
        local_repo.git.checkout('-B', branch_name)
        local_repo.git.add('-A')
        if not local_repo.is_dirty(untracked_files=True):
            raise PullRequestError(
                "No code changes were produced, so GitHub cannot create a pull request. "
                "The fix must modify at least one tracked or new file."
            )

        local_repo.git.commit('-m', f"Fix: Auto-resolved #{issue_num}")
        remote_url = f"https://x-access-token:{token}@github.com/{owner}/{repo_name}.git"
        if "origin" in [r.name for r in local_repo.remotes]:
            local_repo.remote("origin").set_url(remote_url)
        else:
            local_repo.create_remote("origin", remote_url)
        local_repo.git.push('--set-upstream', 'origin', branch_name)
        print(f"[Git] Successfully pushed branch {branch_name} to GitHub remote.")

        # 2. Create Pull Request on GitHub
        auth = Auth.Token(token)
        g = Github(auth=auth)
        repo = g.get_repo(repo_full_name)
        
        default_branch = repo.default_branch
        for existing_pr in repo.get_pulls(state="open"):
            if existing_pr.head.ref == branch_name:
                return existing_pr.html_url

        pr = repo.create_pull(
            title=f"Fix: Auto-resolved #{issue_num}",
            body=f"Automated resolution generated by Smart GitHub Issue Resolver.\n\nSummary:\n{patch_summary}",
            head=branch_name,
            base=default_branch
        )
        return pr.html_url
    except Exception as e:
        if isinstance(e, PullRequestError):
            raise
        raise PullRequestError(f"Failed to create GitHub PR: {e}") from e


def inspect_repository(repo_path: str) -> Dict[str, Any]:
    """
    Scans repository directory and returns list of source files and file tree.
    """
    abs_path = os.path.abspath(repo_path)
    if not os.path.exists(abs_path):
        return {"file_tree": [], "files": {}}

    file_tree = []
    files_content = {}
    ignore_dirs = {'.git', '__pycache__', '.pytest_cache', 'venv', '.venv', 'node_modules'}
    
    for root, dirs, files in os.walk(abs_path):
        dirs[:] = [d for d in dirs if d not in ignore_dirs]
        for file in files:
            if file.endswith(('.py', '.js', '.ts', '.jsx', '.tsx', '.json', '.md')):
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, abs_path).replace("\\", "/")
                file_tree.append(rel_path)
                try:
                    with open(full_path, 'r', encoding='utf-8') as f:
                        files_content[rel_path] = f.read()
                except Exception:
                    pass

    return {
        "file_tree": sorted(file_tree),
        "files": files_content
    }

def apply_patch_to_file(repo_path: str, rel_filepath: str, new_content: str) -> bool:
    """
    Writes updated file content directly to target file inside the repository.
    """
    full_path = os.path.join(os.path.abspath(repo_path), rel_filepath)
    try:
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        return True
    except Exception as e:
        print(f"Error writing patch to {full_path}: {e}")
        return False
